name: X-Browser VRT
on:
  workflow_dispatch:
  schedule:
    # NOTE: timezone is in UTC
    # https://crontab.guru/#0_12_*_*_4
    - cron: "0 12 * * 4"
jobs:
  x-browser-vrt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 3

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: v20.9.0
          cache: yarn
      - name: node_modules cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-cache-
      - name: install dependencies
        run: yarn install --immutable

      - name: set $SHA7
        run: echo "SHA7=$(git log --format=%h --no-merges --max-count 1)" >> $GITHUB_ENV
      - name: set $URL_STORYBOOK
        run: echo "URL_STORYBOOK="https://${SHA7}.ods.dev"" >> $GITHUB_ENV
      - name: set $DATE
        run: echo "DATE=$(date '+%A %B %d, %Y')" >> $GITHUB_ENV

      - name: visual regression test
        env:
          APPLITOOLS_API_KEY: ${{ secrets.OKTA_474937 }}
          APPLITOOLS_BATCH_ID: ${{ github.env.SHA7 }}
        run: yarn workspace @okta/odyssey-storybook eyes-storybook --conf ./applitools.xbrowser.config.js --storybook-url ${{ env.URL_STORYBOOK }}
